name: Update Dockerfiles

on:
  schedule:
    # Allows to Run every day at 9:00 am PST
    - cron:  '0 17 * * *'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows to run this workflow on script updates
  pull_request:
    paths:
      - 'LambdaRuntimeDockerfiles/update-dockerfile.ps1'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NET_5_AMD64_Dockerfile: "LambdaRuntimeDockerfiles/Images/net5/amd64/Dockerfile"
      NET_6_AMD64_Dockerfile: "LambdaRuntimeDockerfiles/Images/net6/amd64/Dockerfile"
      NET_6_ARM64_Dockerfile: "LambdaRuntimeDockerfiles/Images/net6/arm64/Dockerfile"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Update Dockerfiles if newer version of ASP.NET Core is available
      - name: Update dockerfiles
        id: update-dockerfiles
        shell: pwsh
        run: |
          .\LambdaRuntimeDockerfiles/update-dockerfile.ps1 -Dockerfile ${{ env.NET_5_AMD64_Dockerfile }}
          .\LambdaRuntimeDockerfiles/update-dockerfile.ps1 -Dockerfile ${{ env.NET_6_AMD64_Dockerfile }}
          .\LambdaRuntimeDockerfiles/update-dockerfile.ps1 -Dockerfile ${{ env.NET_6_ARM64_Dockerfile }}
          git diff --exit-code --no-pager "**/*Dockerfile"
          if ($? -eq $false) { exit 1 }

      # Push the updated Dockerfiles to the repository
      - name: Commit and Push
        id: commit-push
        run: |
          git config --global user.email "github-aws-sdk-dotnet-automation@amazon.com"
          git config --global user.name "aws-sdk-dotnet-automation"
          branch=chore/update-Dockerfiles-$(date +'%Y-%m-%dT%H-%M-%S')
          git checkout -b $branch
          git add "**/*Dockerfile"
          git commit -m "chore: ASP.NET Core version update in Dockerfiles"
          git push origin $branch
          echo "::set-output name=BRANCH::$branch"

      # Create a Pull Request from the pushed branch
      - name: Pull Request
        id: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ steps.commit-push.outputs.BRANCH }}
          destination_branch: "master"
          pr_title: 'chore: ASP.NET Core version update in Dockerfiles'
          pr_body: "This PR updates the Dockerfiles to use the latest ASP.NET Core version. Verify listed Dockerfiles that they have correct version and matching SHA256 checksum for ASP.NET Core runtime. \n\nAll .NET versions https://dotnet.microsoft.com/en-us/download/dotnet\n\n*Description of changes:*\n${{join(steps.update-dockerfiles.outputs.*, '\n')}}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "auto-pr"
